name: Tinyphone Build

on:
  push: 
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  tinyphone_win_job:
    name: Build Tinyphone Windows
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '1'
        submodules: 'recursive'

    - name: Restore Boost Cache
      uses: actions/cache@v3
      id: cache-boost
      with:
        path: C:\local\boost_1_74_0
        key: boost-74
    - name: Install Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        # Use the boost_1_74_0-msvc-14.1-64.exe for Windows 2019
        $Url = "https://onboardcloud.dl.sourceforge.net/project/boost/boost-binaries/1.74.0/boost_1_74_0-msvc-14.2-32.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost_1_74_0"

    - name: Install Scoop & Binaries
      run : |
        [Net.ServicePointManager]::SecurityProtocol =[Net.SecurityProtocolType]::Tls12 ; 
        (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', "install_scoop.ps1");
        .\install_scoop.ps1 -RunAsAdmin
        scoop install curl wget cmake unzip make;

    - name: Install wixtoolset
      run : |
        $Url = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\wix311.exe")
        Start-Process -Wait -FilePath "$env:TEMP\wix311.exe" "/install","/quiet","/norestart"

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Configure build for Windows MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build Project
      run : |
        $env:CodeDir=$(pwd)
        .\distribution\docker\release.ps1 -ErrorAction Stop

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tinyphone.msi
        path: |
          ./tinyphone-installer/bin/Release/tinyphone_installer.msi

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        artifacts: "./tinyphone/Release/tinyphone.exe,tinyphone-installer/bin/Release/tinyphone_installer.msi"
        draft: true
        allowUpdates: true
        token: ${{ secrets.GH_TOKEN }}
